git:
  autoFetch: false
  pagers:
    - pager: delta --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
customCommands:
  - key: '<c-l>'
    context: 'files'
    command: 'lumen draft | pbcopy'
    loadingText: 'Generating message...'
  - key: '<c-k>'
    context: 'files'
    command: 'lumen draft -c {{.Form.Context | quote}} | pbcopy'
    loadingText: 'Generating message...'
    prompts:
      - type: 'input'
        title: 'Context'
        key: 'Context'
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#7aa2f7"
      - "bold"
    inactiveBorderColor:
      - "#a9b1d6"
    searchingActiveBorderColor:
      - "#7aa2f7"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#292e42"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#3b4261"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#3b4261"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#a9b1d6"
